PACKAGE_NAME = "ModelCatConnector"

DEFAULT_AWS_REGION = "us-east-2"
DEFAULT_AWS_FORMAT = "json"

MAX_DATASET_SIZE = 100e9
MAX_DATASET_SIZE_STR = "100 GB"

OAUTH_TOKEN_RE = r"^(\d+)_([0-9a-fA-F]{40})$"
